// ── Sage · Plan History ─────────────────────────────────────────────────────
// Charts built from plan_history.json (generated by build_plan_history.py from the
// Fidelity/eMoney annual-review PDFs). Plain SVG, no dependencies.

const VERSION_HISTORY = [
    { version: 'v1.0', description: 'Initial release — net worth by asset type, modeled outflows, projected portfolio and net cash flow from the Fidelity annual reviews.' },
];
const COMMIT = '4af46a1';

const SVGNS = 'http://www.w3.org/2000/svg';
let DATA = null;
let nwScope = 'all';
let adjusted = true;      // add the inherited IRA back into post-conversion actuals

// Stack order is bottom → top. Colors are tokens from plan.css (validated palette).
const NW_SERIES = [
    { key: 'real_estate',  name: 'Real estate & other',  color: 'var(--viz-neutral)', realEstate: true },
    { key: 'retirement',   name: 'Retirement accounts',  color: 'var(--s1)' },
    { key: 'bda_ira',      name: 'Inherited IRA (BDA)',  color: 'var(--s2)' },
    { key: 'annuities',    name: 'Annuities',            color: 'var(--s3)' },
    { key: 'taxable_cash', name: 'Taxable & cash',       color: 'var(--s4)' },
];
const SP_SERIES = [
    { key: 'living',    name: 'Living expenses',    color: 'var(--s1)' },
    { key: 'insurance', name: 'Insurance premiums', color: 'var(--s2)' },
    { key: 'taxes',     name: 'Taxes',              color: 'var(--s3)' },
    { key: 'other',     name: 'Education & other',  color: 'var(--s4)' },
];

// ── helpers ─────────────────────────────────────────────────────────────────
const $ = id => document.getElementById(id);
const esc = s => String(s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));

function svgEl(tag, attrs, parent) {
    const e = document.createElementNS(SVGNS, tag);
    for (const k in (attrs || {})) e.setAttribute(k, attrs[k]);
    if (parent) parent.appendChild(e);
    return e;
}

function money(v) {                       // compact: $3.38M, $945K
    const a = Math.abs(v);
    let s;
    if (a >= 1e6) s = '$' + (a / 1e6).toFixed(a >= 1e7 ? 1 : 2).replace(/\.0+$/, '').replace(/(\.\d)0$/, '$1') + 'M';
    else if (a >= 1e3) s = '$' + Math.round(a / 1e3) + 'K';
    else s = '$' + Math.round(a);
    return (v < 0 ? '−' : '') + s;
}
function full(v) { return (v < 0 ? '−' : '') + '$' + Math.round(Math.abs(v)).toLocaleString('en-US'); }
function signed(v) { return (v >= 0 ? '+' : '−') + '$' + Math.round(Math.abs(v)).toLocaleString('en-US'); }

function niceScale(min, max, n) {
    const span = (max - min) || 1;
    const raw = span / n;
    const mag = Math.pow(10, Math.floor(Math.log10(raw)));
    const r = raw / mag;
    const step = (r <= 1 ? 1 : r <= 2 ? 2 : r <= 2.5 ? 2.5 : r <= 5 ? 5 : 10) * mag;
    const lo = Math.floor(min / step + 1e-9) * step;
    const hi = Math.ceil(max / step - 1e-9) * step;
    const ticks = [];
    for (let v = lo; v <= hi + step * 1e-6; v += step) ticks.push(Math.round(v * 1e6) / 1e6);
    return { lo, hi, ticks };
}

function barPath(x, y, w, h, r, round) {   // round: 'top' | 'bottom' | 'none'
    r = Math.max(0, Math.min(r, h / 2, w / 2));
    if (round === 'top')    return `M${x},${y + h}V${y + r}Q${x},${y} ${x + r},${y}H${x + w - r}Q${x + w},${y} ${x + w},${y + r}V${y + h}Z`;
    if (round === 'bottom') return `M${x},${y}V${y + h - r}Q${x},${y + h} ${x + r},${y + h}H${x + w - r}Q${x + w},${y + h} ${x + w},${y + h - r}V${y}Z`;
    return `M${x},${y}h${w}v${h}h${-w}Z`;
}

// ── tooltip ─────────────────────────────────────────────────────────────────
function showTip(html, x, y) {
    const t = $('plTip');
    t.innerHTML = html;
    t.hidden = false;
    const r = t.getBoundingClientRect();
    let left = x + 16, top = y + 16;
    if (left + r.width > window.innerWidth - 8) left = x - r.width - 16;
    if (top + r.height > window.innerHeight - 8) top = window.innerHeight - r.height - 8;
    t.style.left = Math.max(8, left) + 'px';
    t.style.top = Math.max(8, top) + 'px';
}
function hideTip() { $('plTip').hidden = true; }
const swatch = c => `<i class="pl-swatch" style="background:${c}"></i>`;

// ── notes markers (numbered discs on the chart + a legend list beneath) ──────
function drawDiscs(svg, cx, cy, nums, onEnter) {
    nums.forEach((n, j) => {
        const x = cx + (j - (nums.length - 1) / 2) * 20;
        const g = svgEl('g', {}, svg);
        svgEl('circle', { cx: x, cy, r: 9, class: 'pl-disc' }, g);
        const t = svgEl('text', { x, y: cy + 3.5, class: 'pl-disc-n' }, g);
        t.textContent = n;
        g.addEventListener('mousemove', e => onEnter(n, e));
        g.addEventListener('mouseleave', hideTip);
    });
}
function renderNotes(host, items) {
    host.innerHTML = items.map(it =>
        `<div class="pl-notes-item"><span class="pl-notes-n">${it.n}</span><div><b>${esc(it.title)}</b>${esc(it.text)}</div></div>`
    ).join('');
    host.hidden = !items.length;
}

// ── stacked columns ─────────────────────────────────────────────────────────
// o: { cats:[{label, sub}], series:[{name,color,values[]}], height, topPad, noteFor(i)->[{n,title,text}], tipHead(i), tipFoot(i) }
function stackedColumns(host, o) {
    host.innerHTML = '';
    const W = host.clientWidth || 600, H = o.height || 320;
    const m = { l: 50, r: 10, t: o.topPad || 30, b: 40 };
    const svg = svgEl('svg', { width: W, height: H, role: 'img', 'aria-label': o.aria }, host);
    const n = o.cats.length;
    const totals = o.cats.map((_, i) => o.series.reduce((s, se) => s + se.values[i], 0));
    const sc = niceScale(0, Math.max(...totals) * 1.02, 4);
    const y = v => m.t + (H - m.t - m.b) * (1 - (v - sc.lo) / (sc.hi - sc.lo));

    sc.ticks.forEach(v => {
        svgEl('line', { x1: m.l, x2: W - m.r, y1: y(v), y2: y(v), class: v === 0 ? 'pl-axis' : 'pl-grid' }, svg);
        const t = svgEl('text', { x: m.l - 8, y: y(v) + 4, 'text-anchor': 'end' }, svg);
        t.textContent = money(v);
    });

    const bw = (W - m.l - m.r) / n;
    const barW = Math.min(24, bw * 0.6);
    const hits = [];
    o.cats.forEach((c, i) => {
        const cx = m.l + bw * i + bw / 2, x0 = cx - barW / 2;
        let cum = 0;
        const segs = o.series.map((se, k) => ({ se, k, v: se.values[i] })).filter(s => s.v > 0);
        segs.forEach((s, idx) => {
            const yTop = y(cum + s.v), yBot = y(cum);
            const gap = idx === 0 ? 0 : 2;                        // 2px surface gap between segments
            const h = Math.max(1, yBot - yTop - gap);
            const p = svgEl('path', { d: barPath(x0, yTop, barW, h, 4, idx === segs.length - 1 ? 'top' : 'none') }, svg);
            p.style.fill = s.se.color;
            cum += s.v;
        });
        if (bw >= 46) {
            const t = svgEl('text', { x: cx, y: y(cum) - 7, 'text-anchor': 'middle', class: 'pl-total' }, svg);
            t.textContent = money(totals[i]);
        }
        const l1 = svgEl('text', { x: cx, y: H - m.b + 16, 'text-anchor': 'middle' }, svg);
        l1.textContent = c.label;
        const l2 = svgEl('text', { x: cx, y: H - m.b + 29, 'text-anchor': 'middle' }, svg);
        l2.textContent = bw < 40 ? "'" + c.sub.slice(2) : c.sub;   // '19 when columns are narrow

        const hit = svgEl('rect', { x: m.l + bw * i, y: m.t - 6, width: bw, height: H - m.t - m.b + 6, class: 'pl-hit' }, svg);
        hits.push(hit);
        hit.addEventListener('mousemove', e => {
            hits.forEach(h => h.classList.remove('on'));
            hit.classList.add('on');
            let html = `<div class="pl-tip-title">${esc(c.label)} ${esc(c.sub)}</div>` + (o.tipHead ? o.tipHead(i) : '');
            for (let k = o.series.length - 1; k >= 0; k--) {
                const se = o.series[k];
                if (se.values[i] > 0) html += `<div class="pl-tip-row"><span>${swatch(se.color)}${esc(se.name)}</span><b>${full(se.values[i])}</b></div>`;
            }
            html += `<div class="pl-tip-row pl-tip-total"><span>Total</span><b>${full(totals[i])}</b></div>`;
            if (o.tipFoot) html += o.tipFoot(i);
            showTip(html, e.clientX, e.clientY);
        });
        hit.addEventListener('mouseleave', () => { hit.classList.remove('on'); hideTip(); });

        const notes = o.noteFor ? o.noteFor(i) : [];
        if (notes.length) drawDiscs(svg, cx, 12, notes.map(x => x.n), (num, e) => {
            const it = notes.find(x => x.n === num);
            showTip(`<div class="pl-tip-title">${esc(it.title)}</div>${esc(it.text)}`, e.clientX, e.clientY);
        });
    });
}

// ── line chart (projected portfolio) ─────────────────────────────────────────
function lineChart(host, rows) {
    host.innerHTML = '';
    const W = host.clientWidth || 600, H = 300;
    const m = { l: 50, r: 56, t: 16, b: 44 };
    const svg = svgEl('svg', { width: W, height: H, role: 'img', 'aria-label': 'Projected total portfolio assets by year' }, host);
    const n = rows.length;
    const xs = i => m.l + (W - m.l - m.r) * i / (n - 1);
    const sc = niceScale(0, Math.max(...rows.map(r => r.portfolio)) * 1.02, 4);
    const y = v => m.t + (H - m.t - m.b) * (1 - (v - sc.lo) / (sc.hi - sc.lo));

    sc.ticks.forEach(v => {
        svgEl('line', { x1: m.l, x2: W - m.r, y1: y(v), y2: y(v), class: v === 0 ? 'pl-axis' : 'pl-grid' }, svg);
        const t = svgEl('text', { x: m.l - 8, y: y(v) + 4, 'text-anchor': 'end' }, svg);
        t.textContent = money(v);
    });
    const every = W < 520 ? 10 : 5;
    rows.forEach((r, i) => {
        if (i !== 0 && r.year % every !== 0) return;
        const a = svgEl('text', { x: xs(i), y: H - m.b + 16, 'text-anchor': 'middle' }, svg);
        a.textContent = r.year;
        const b = svgEl('text', { x: xs(i), y: H - m.b + 29, 'text-anchor': 'middle' }, svg);
        b.textContent = 'age ' + r.age;
    });

    const pts = rows.map((r, i) => `${xs(i).toFixed(1)},${y(r.portfolio).toFixed(1)}`);
    const area = svgEl('path', { d: `M${pts.join('L')}L${xs(n - 1)},${y(0)}L${xs(0)},${y(0)}Z`, opacity: 0.1 }, svg);
    area.style.fill = 'var(--s1)';
    const line = svgEl('path', { d: 'M' + pts.join('L'), fill: 'none', 'stroke-width': 2, 'stroke-linejoin': 'round', 'stroke-linecap': 'round' }, svg);
    line.style.stroke = 'var(--s1)';

    const last = rows[n - 1];
    const ring = svgEl('circle', { cx: xs(n - 1), cy: y(last.portfolio), r: 6 }, svg); ring.style.fill = 'var(--viz-surface)';
    const dot = svgEl('circle', { cx: xs(n - 1), cy: y(last.portfolio), r: 4 }, svg); dot.style.fill = 'var(--s1)';
    const lab = svgEl('text', { x: xs(n - 1) + 10, y: y(last.portfolio) + 4, class: 'pl-total' }, svg);
    lab.textContent = money(last.portfolio);

    // hover: crosshair + dot
    const cross = svgEl('line', { y1: m.t, y2: y(0), class: 'pl-cross', visibility: 'hidden' }, svg);
    const hRing = svgEl('circle', { r: 7, visibility: 'hidden' }, svg); hRing.style.fill = 'var(--viz-surface)';
    const hDot = svgEl('circle', { r: 5, visibility: 'hidden' }, svg); hDot.style.fill = 'var(--s1)';
    const hit = svgEl('rect', { x: m.l, y: m.t, width: W - m.l - m.r, height: H - m.t - m.b, fill: 'transparent' }, svg);
    hit.addEventListener('mousemove', e => {
        const box = hit.getBoundingClientRect();
        const i = Math.max(0, Math.min(n - 1, Math.round((e.clientX - box.left) / box.width * (n - 1))));
        const r = rows[i];
        cross.setAttribute('x1', xs(i)); cross.setAttribute('x2', xs(i)); cross.setAttribute('visibility', 'visible');
        [hRing, hDot].forEach(c => { c.setAttribute('cx', xs(i)); c.setAttribute('cy', y(r.portfolio)); c.setAttribute('visibility', 'visible'); });
        showTip(`<div class="pl-tip-title">${r.year} · age ${r.age}</div>
            <div class="pl-tip-row"><span>${swatch('var(--s1)')}Portfolio</span><b>${full(r.portfolio)}</b></div>
            <div class="pl-tip-row"><span>Inflows</span><b>${full(r.inflows)}</b></div>
            <div class="pl-tip-row"><span>Outflows</span><b>${full(r.outflows)}</b></div>
            <div class="pl-tip-row pl-tip-total"><span>Net cash flow</span><b>${signed(r.net)}</b></div>`, e.clientX, e.clientY);
    });
    hit.addEventListener('mouseleave', () => {
        [cross, hRing, hDot].forEach(c => c.setAttribute('visibility', 'hidden'));
        hideTip();
    });
}

// ── net cash flow bars (diverging around zero) ───────────────────────────────
function cashFlowBars(host, rows, notes) {
    host.innerHTML = '';
    const W = host.clientWidth || 600, H = 300;
    const m = { l: 50, r: 10, t: 34, b: 44 };
    const svg = svgEl('svg', { width: W, height: H, role: 'img', 'aria-label': 'Projected net cash flow by year' }, host);
    const n = rows.length;
    const vals = rows.map(r => r.net);
    const sc = niceScale(Math.min(0, ...vals) * 1.05, Math.max(0, ...vals) * 1.05, 4);
    const y = v => m.t + (H - m.t - m.b) * (1 - (v - sc.lo) / (sc.hi - sc.lo));

    sc.ticks.forEach(v => {
        svgEl('line', { x1: m.l, x2: W - m.r, y1: y(v), y2: y(v), class: v === 0 ? 'pl-axis' : 'pl-grid' }, svg);
        const t = svgEl('text', { x: m.l - 8, y: y(v) + 4, 'text-anchor': 'end' }, svg);
        t.textContent = money(v);
    });

    const bw = (W - m.l - m.r) / n;
    const barW = Math.min(24, bw * 0.65);
    const every = W < 520 ? 10 : 5;
    const hits = [];
    rows.forEach((r, i) => {
        const cx = m.l + bw * i + bw / 2, x0 = cx - barW / 2;
        const y0 = y(0), yv = y(r.net);
        const h = Math.max(1, Math.abs(yv - y0));
        const p = svgEl('path', { d: r.net >= 0 ? barPath(x0, yv, barW, h, 4, 'top') : barPath(x0, y0, barW, h, 4, 'bottom') }, svg);
        p.style.fill = r.net >= 0 ? 'var(--div-pos)' : 'var(--div-neg)';
        if (i === 0 || r.year % every === 0) {
            const a = svgEl('text', { x: cx, y: H - m.b + 16, 'text-anchor': 'middle' }, svg); a.textContent = r.year;
            const b = svgEl('text', { x: cx, y: H - m.b + 29, 'text-anchor': 'middle' }, svg); b.textContent = 'age ' + r.age;
        }
        const hit = svgEl('rect', { x: m.l + bw * i, y: m.t - 6, width: bw, height: H - m.t - m.b + 6, class: 'pl-hit' }, svg);
        hits.push(hit);
        hit.addEventListener('mousemove', e => {
            hits.forEach(h2 => h2.classList.remove('on')); hit.classList.add('on');
            showTip(`<div class="pl-tip-title">${r.year} · age ${r.age}</div>
                <div class="pl-tip-row"><span>Inflows</span><b>${full(r.inflows)}</b></div>
                <div class="pl-tip-row"><span>Outflows</span><b>${full(r.outflows)}</b></div>
                <div class="pl-tip-row pl-tip-total"><span>${swatch(r.net >= 0 ? 'var(--div-pos)' : 'var(--div-neg)')}${r.net >= 0 ? 'Surplus' : 'Shortfall'}</span><b>${signed(r.net)}</b></div>`,
                e.clientX, e.clientY);
        });
        hit.addEventListener('mouseleave', () => { hit.classList.remove('on'); hideTip(); });

        const note = notes.find(nt => nt.year === r.year);
        if (note) drawDiscs(svg, cx, 12, [note.n], (num, e) =>
            showTip(`<div class="pl-tip-title">${esc(note.title)}</div>${esc(note.text)}`, e.clientX, e.clientY));
    });
}

// ── table view ──────────────────────────────────────────────────────────────
function tableHtml(head, rows) {
    return '<table><thead><tr>' + head.map(h => `<th>${esc(h)}</th>`).join('') + '</tr></thead><tbody>' +
        rows.map(r => '<tr>' + r.map(c => `<td>${esc(c)}</td>`).join('') + '</tr>').join('') + '</tbody></table>';
}


// ── forecast vs reality ─────────────────────────────────────────────────────
const YEAR_MS = 365.25 * 864e5;
const dateMs = d => new Date(d + 'T00:00:00').getTime();

// Portfolio as the plan defines it: net worth less real estate & personal property.
function actualPortfolio(r) { return r.net_worth - r.groups.real_estate; }

// Inherited-IRA add-back: last balance before the annuity, applied to reports on/after the conversion.
function annuityAdjustment() {
    const R = DATA.reports;
    const conv = R.findIndex((r, i) => i > 0 && r.groups.bda_ira === 0 && R[i - 1].groups.bda_ira > 0);
    return conv < 0 ? { idx: R.length, amount: 0 } : { idx: conv, amount: R[conv - 1].groups.bda_ira };
}

// A vintage's forecast for `ms`: year 1 is the 12 months after its report date; value 0 is its opening balance.
function forecastAt(v, ms) {
    const t = (ms - dateMs(v.date)) / YEAR_MS, path = v.forecast.path, k = Math.floor(t);
    const V = n => (n === 0 ? v.forecast.boy : (path[n - 1] ? path[n - 1].portfolio : null));
    const a = V(k), b = V(k + 1);
    return a == null || b == null ? null : a + (b - a) * (t - k);
}

// errors[i][j] = actual/forecast − 1 for vintage i judged against report j (j > i), plus predicted/actual values
function forecastGrid() {
    const R = DATA.reports, adj = annuityAdjustment(), grid = [];
    R.forEach((v, i) => {
        grid[i] = [];
        R.forEach((r, j) => {
            if (j <= i) { grid[i][j] = null; return; }
            const pred = forecastAt(v, dateMs(r.date));
            let act = actualPortfolio(r);
            if (adjusted && j >= adj.idx && i < adj.idx) act += adj.amount;
            grid[i][j] = pred == null ? null : { pred, act, err: act / pred - 1 };
        });
    });
    return grid;
}
const pct = (e, d = 0) => {
    const v = Math.abs(e * 100).toFixed(d);
    return (Number(v) === 0 ? '' : e >= 0 ? '+' : '−') + v + '%';     // no '−0%'
};
const median = a => { const s = [...a].sort((x, y) => x - y), m = s.length >> 1; return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2; };

function forecastChart(host) {
    host.innerHTML = '';
    const R = DATA.reports, adj = annuityAdjustment(), n = R.length;
    const W = host.clientWidth || 600, H = 380;
    const m = { l: 50, r: 76, t: 34, b: 30 };
    const svg = svgEl('svg', { width: W, height: H, role: 'img', 'aria-label': 'Forecast portfolio paths from each report against actual balances' }, host);
    const t0 = dateMs(R[0].date), t1 = dateMs(R[n - 1].date);
    const xs = ms => m.l + (W - m.l - m.r) * (ms - t0) / (t1 - t0);

    // vintage lines, clipped at the newest report date
    const lines = [];
    R.slice(0, n - 1).forEach((v, i) => {
        const pts = [[dateMs(v.date), v.forecast.boy]];
        for (let k = 1; k <= v.forecast.path.length; k++) {
            const ms = dateMs(v.date) + k * YEAR_MS;
            if (ms >= t1) { pts.push([t1, forecastAt(v, t1)]); break; }
            pts.push([ms, v.forecast.path[k - 1].portfolio]);
        }
        lines.push({ i, pts });
    });
    const actual = R.map(r => actualPortfolio(r));
    const adjVals = R.map((r, j) => (j >= adj.idx ? actual[j] + adj.amount : null));
    const all = [...actual, ...adjVals.filter(x => x != null), ...lines.flatMap(l => l.pts.map(p => p[1]))];
    const sc = niceScale(Math.min(...all) * 0.9, Math.max(...all) * 1.04, 5);
    const y = v => m.t + (H - m.t - m.b) * (1 - (v - sc.lo) / (sc.hi - sc.lo));

    sc.ticks.forEach(v => {
        svgEl('line', { x1: m.l, x2: W - m.r, y1: y(v), y2: y(v), class: 'pl-grid' }, svg);
        svgEl('text', { x: m.l - 8, y: y(v) + 4, 'text-anchor': 'end' }, svg).textContent = money(v);
    });
    for (let yr = new Date(t0).getFullYear() + 1; yr <= new Date(t1).getFullYear(); yr++) {
        const x = xs(new Date(yr, 0, 1).getTime());
        svgEl('text', { x, y: H - m.b + 18, 'text-anchor': 'middle' }, svg).textContent = yr;
    }
    svgEl('line', { x1: m.l, x2: W - m.r, y1: y(sc.lo), y2: y(sc.lo), class: 'pl-axis' }, svg);

    lines.forEach(l => {
        const p = svgEl('path', { d: 'M' + l.pts.map(q => `${xs(q[0]).toFixed(1)},${y(q[1]).toFixed(1)}`).join('L'), class: 'pl-vline' }, svg);
        p.style.stroke = `var(--v${l.i})`;
    });

    // actual line, adjusted continuation, dots
    svgEl('path', { d: 'M' + R.map((r, j) => `${xs(dateMs(r.date))},${y(actual[j])}`).join('L'), class: 'pl-actual' }, svg);
    if (adj.idx < n) {
        const seg = [[adj.idx - 1, actual[adj.idx - 1] ], ...R.map((r, j) => [j, adjVals[j]]).filter(q => q[1] != null)];
        svgEl('path', { d: 'M' + seg.map(q => `${xs(dateMs(R[q[0]].date))},${y(q[1])}`).join('L'), class: 'pl-adj' }, svg);
    }
    R.forEach((r, j) => svgEl('circle', { cx: xs(dateMs(r.date)), cy: y(actual[j]), r: 4.5, class: 'pl-dot' }, svg));
    R.forEach((r, j) => { if (adjVals[j] != null) svgEl('circle', { cx: xs(dateMs(r.date)), cy: y(adjVals[j]), r: 4.5, class: 'pl-dot-h' }, svg); });

    // direct labels at the right edge
    svgEl('text', { x: xs(t1) + 10, y: y(actual[n - 1]) + 4, class: 'pl-lbl' }, svg).textContent = money(actual[n - 1]);
    if (adjVals[n - 1] != null) svgEl('text', { x: xs(t1) + 10, y: y(adjVals[n - 1]) + 4, class: 'pl-lbl' }, svg).textContent = money(adjVals[n - 1]);

    // hover: nearest report date
    const cross = svgEl('line', { y1: m.t, y2: y(sc.lo), class: 'pl-cross', visibility: 'hidden' }, svg);
    const hit = svgEl('rect', { x: m.l - 10, y: m.t, width: W - m.l - m.r + 20, height: H - m.t - m.b, fill: 'transparent' }, svg);
    const grid = forecastGrid();
    hit.addEventListener('mousemove', e => {
        const box = hit.getBoundingClientRect(), px = e.clientX - box.left + m.l - 10;
        let j = 0, best = 1e9;
        R.forEach((r, k) => { const d = Math.abs(xs(dateMs(r.date)) - px); if (d < best) { best = d; j = k; } });
        const cx = xs(dateMs(R[j].date));
        cross.setAttribute('x1', cx); cross.setAttribute('x2', cx); cross.setAttribute('visibility', 'visible');
        let html = `<div class="pl-tip-title">${esc(R[j].label)}</div>
            <div class="pl-tip-row"><span><i class="pl-mark solid"></i>Actual</span><b>${full(actual[j])}</b></div>`;
        if (adjVals[j] != null) html += `<div class="pl-tip-row"><span><i class="pl-mark hollow"></i>Actual + inherited IRA</span><b>${full(adjVals[j])}</b></div>`;
        const rows = [];
        for (let i = 0; i < j; i++) if (grid[i][j]) rows.push([i, grid[i][j]]);
        if (rows.length) html += '<div class="pl-tip-note">Forecast made in…</div>';
        rows.forEach(([i, c]) => html += `<div class="pl-tip-row"><span>${swatch(`var(--v${i})`)}${esc(R[i].label)}</span><b>${money(c.pred)} · ${pct(c.err)}</b></div>`);
        showTip(html, e.clientX, e.clientY);
    });
    hit.addEventListener('mouseleave', () => { cross.setAttribute('visibility', 'hidden'); hideTip(); });
}

function forecastMatrix(host) {
    const R = DATA.reports, grid = forecastGrid(), n = R.length;
    const cell = c => {
        if (!c) return '<td class="blank">·</td>';
        const a = Math.min(Math.abs(c.err) / 0.25, 1) * 62;
        const col = c.err >= 0 ? 'var(--div-pos)' : 'var(--div-neg)';
        return `<td style="background:color-mix(in srgb, ${col} ${a.toFixed(0)}%, transparent)" title="Forecast ${full(c.pred)} · actual ${full(c.act)}">${pct(c.err)}</td>`;
    };
    let h = '<table><thead><tr><th>Forecast made in</th>' + R.slice(1).map(r => `<th>${esc(r.label)}</th>`).join('') + '<th>Avg. miss</th></tr></thead><tbody>';
    for (let i = 0; i < n - 1; i++) {
        const errs = grid[i].filter(Boolean).map(c => c.err);
        h += `<tr><td class="rowhead">${esc(R[i].label)}${i === 0 ? ' *' : ''}</td>` +
            R.slice(1).map((r, jj) => cell(grid[i][jj + 1])).join('') +
            `<td class="avg">${errs.length ? (errs.reduce((s, e) => s + Math.abs(e), 0) / errs.length * 100).toFixed(0) + '%' : '—'}</td></tr>`;
    }
    host.innerHTML = h + '</tbody></table>';
}

function forecastTiles(host) {
    const grid = forecastGrid();
    const errs = [];
    grid.forEach((row, i) => { if (i > 0) row.forEach(c => c && errs.push(c.err)); });   // Aug 2019 row excluded (see note)
    const within = lim => errs.filter(e => Math.abs(e) <= lim).length;
    const R = DATA.reports, later = [];   // long range = judged 3.75+ years after the forecast was made
    grid.forEach((row, i) => row.forEach((c, j) => { if (c && i > 0 && (dateMs(R[j].date) - dateMs(R[i].date)) / YEAR_MS >= 3.75) later.push(c.err); }));
    host.innerHTML = [
        ['Within ±5% of reality', `${within(0.05)} of ${errs.length}`, `and ${within(0.10)} of ${errs.length} within ±10%`],
        ['Too high vs too low', `${errs.filter(e => e < 0).length} / ${errs.filter(e => e > 0).length}`, 'forecasts above / below what happened'],
        ['Long range (about 4+ years)', later.length ? `${pct(median(later), 1)} median` : '—', `across ${later.length} comparisons; ${later.filter(e => Math.abs(e) <= 0.05).length} within ±5%`],
    ].map(t => `<div class="pl-tile"><div class="pl-tile-label">${esc(t[0])}</div><div class="pl-tile-value">${esc(t[1])}</div><div class="pl-tile-sub">${esc(t[2])}</div></div>`).join('');
}

// ── grouped columns (plan vs actual) ─────────────────────────────────────────
function groupedColumns(host, o) {
    host.innerHTML = '';
    const W = host.clientWidth || 600, H = 300;
    const m = { l: 50, r: 10, t: 24, b: 34 };
    const svg = svgEl('svg', { width: W, height: H, role: 'img', 'aria-label': o.aria }, host);
    const n = o.cats.length;
    const sc = niceScale(0, Math.max(...o.series.flatMap(s => s.values.filter(v => v != null))) * 1.1, 4);
    const y = v => m.t + (H - m.t - m.b) * (1 - (v - sc.lo) / (sc.hi - sc.lo));
    sc.ticks.forEach(v => {
        svgEl('line', { x1: m.l, x2: W - m.r, y1: y(v), y2: y(v), class: v === 0 ? 'pl-axis' : 'pl-grid' }, svg);
        svgEl('text', { x: m.l - 8, y: y(v) + 4, 'text-anchor': 'end' }, svg).textContent = money(v);
    });
    const bw = (W - m.l - m.r) / n, k = o.series.length, barW = Math.min(24, (bw * 0.7 - 2 * (k - 1)) / k);
    const hits = [];
    o.cats.forEach((c, i) => {
        const cx = m.l + bw * i + bw / 2, x0 = cx - (k * barW + (k - 1) * 2) / 2;
        o.series.forEach((se, si) => {
            const v = se.values[i]; if (v == null) return;
            const x = x0 + si * (barW + 2), h = Math.max(1, y(0) - y(v));
            svgEl('path', { d: barPath(x, y(v), barW, h, 4, 'top') }, svg).style.fill = se.color;
            if (bw >= 70) { const t = svgEl('text', { x: x + barW / 2, y: y(v) - 6, 'text-anchor': 'middle', class: 'pl-total' }, svg); t.style.fontSize = '10px'; t.textContent = money(v); }
        });
        svgEl('text', { x: cx, y: H - m.b + 18, 'text-anchor': 'middle' }, svg).textContent = c;
        const hit = svgEl('rect', { x: m.l + bw * i, y: m.t - 6, width: bw, height: H - m.t - m.b + 6, class: 'pl-hit' }, svg);
        hits.push(hit);
        hit.addEventListener('mousemove', e => {
            hits.forEach(h2 => h2.classList.remove('on')); hit.classList.add('on');
            let html = `<div class="pl-tip-title">${esc(c)}</div>` +
                o.series.map(se => se.values[i] == null ? '' : `<div class="pl-tip-row"><span>${swatch(se.color)}${esc(se.name)}</span><b>${full(se.values[i])}</b></div>`).join('');
            const a = o.series[0].values[i], b = o.series[1].values[i];
            if (a != null && b != null) html += `<div class="pl-tip-row pl-tip-total"><span>${esc(o.series[1].name)} vs plan</span><b>${pct(b / a - 1)}</b></div>`;
            showTip(html, e.clientX, e.clientY);
        });
        hit.addEventListener('mouseleave', () => { hit.classList.remove('on'); hideTip(); });
    });
}

// ── page assembly ───────────────────────────────────────────────────────────
function legend(host, items) {
    host.innerHTML = items.map(it => `<span>${swatch(it.color)}${esc(it.name)}</span>`).join('');
}

function renderTiles() {
    const R = DATA.reports, last = R[R.length - 1], prev = R[R.length - 2];
    const fin = r => r.net_worth - r.groups.real_estate;
    const dNW = last.net_worth - prev.net_worth, dFin = fin(last) - fin(prev);
    const y1 = last.year1;
    $('plTiles').innerHTML = [
        ['Net worth · ' + last.label, full(last.net_worth), `${signed(dNW)} since ${prev.label}`],
        ['Financial assets (excl. real estate)', full(fin(last)), `${signed(dFin)} (${(dFin / fin(prev) * 100).toFixed(1)}%) since ${prev.label}`],
        ['Annuity income', full(DATA.household.annuity_monthly_after_tax) + ' / mo',
            `after tax · modeled at ${full(last.annuity_income)}/yr gross, replacing the inherited IRA`],
        ['Modeled outflows · ' + last.first_year, full(y1.total),
            `living ${money(y1.living)} · insurance ${money(y1.insurance)} · taxes ${money(y1.taxes)}`],
    ].map(t => `<div class="pl-tile"><div class="pl-tile-label">${esc(t[0])}</div><div class="pl-tile-value">${esc(t[1])}</div><div class="pl-tile-sub">${esc(t[2])}</div></div>`).join('');
}

function drawForecast() {
    const R = DATA.reports, grid = forecastGrid();
    forecastTiles($('fcTiles'));
    forecastChart($('chartFC'));
    legend($('legendFC'), []);
    $('legendFC').innerHTML =
        `<span><i class="pl-mark solid"></i>Actual balance</span>` +
        (adjusted && annuityAdjustment().idx < R.length ? `<span><i class="pl-mark hollow"></i>Actual + inherited IRA (annuity purchase added back)</span>` : '') +
        `<span><i class="pl-grad" style="background:linear-gradient(90deg,var(--v0),var(--v7))"></i>Forecast, ${esc(R[0].label)} → ${esc(R[R.length - 2].label)} (older → newer)</span>`;
    forecastMatrix($('matrixFC'));
    renderNotes($('notesFC2'), DATA.forecast_notes.map((nt, i) => ({ n: i + 1, title: nt.title, text: nt.text })));
    $('tableFC').innerHTML = tableHtml(['Forecast made in', 'Judged at', 'Forecast', 'Actual', 'Miss'],
        R.flatMap((v, i) => grid[i].map((c, j) => c ? [v.label, R[j].label, full(c.pred), full(c.act), pct(c.err, 1)] : null).filter(Boolean)));

    // spending: plan vs Quicken
    const live = (DATA.actuals && DATA.actuals.living) || {};
    const years = [2021, 2022, 2023, 2024, 2025].filter(yr => live[yr] != null);
    const planFor = yr => { const r = [...R].reverse().find(x => x.first_year === yr); return r ? r.year1.living : null; };
    const lvSeries = [
        { name: 'Plan assumption', color: 'var(--viz-neutral)', values: years.map(planFor) },
        { name: 'Quicken actual', color: 'var(--s1)', values: years.map(yr => live[yr]) },
    ];
    groupedColumns($('chartLV'), { cats: years.map(String), series: lvSeries, aria: 'Plan living-expense assumption versus Quicken spending by year' });
    legend($('legendLV'), lvSeries);
    $('tableLV').innerHTML = tableHtml(['Year', 'Plan assumption', 'Quicken actual', 'Actual vs plan'],
        years.map((yr, i) => [yr, full(lvSeries[0].values[i]), full(lvSeries[1].values[i]), pct(lvSeries[1].values[i] / lvSeries[0].values[i] - 1)]));
    $('lvNote').textContent = DATA.spending_note || '';
}

function drawAll() {
    drawForecast();
    const R = DATA.reports;
    const cats = R.map(r => { const [mo, yr] = r.label.split(' '); return { label: mo, sub: yr, date: r.date }; });
    const events = DATA.events.map((e, i) => ({ ...e, n: i + 1 }));

    // Net worth by asset type
    const nwSeries = NW_SERIES.filter(s => nwScope === 'all' || !s.realEstate)
        .map(s => ({ ...s, values: R.map(r => r.groups[s.key]) }));
    stackedColumns($('chartNW'), {
        cats, series: nwSeries, height: 340, topPad: 48,
        aria: 'Net worth by asset type for each annual review',
        noteFor: i => events.filter(e => e.date === R[i].date),
    });
    legend($('legendNW'), nwSeries);
    $('tableNW').innerHTML = tableHtml(['Report', ...nwSeries.map(s => s.name), 'Total'],
        R.map((r, i) => [r.label, ...nwSeries.map(s => full(s.values[i])), full(nwSeries.reduce((a, s) => a + s.values[i], 0))]));
    renderNotes($('notesNW'), events);

    // Modeled outflows
    const spSeries = SP_SERIES.map(s => ({ ...s, values: R.map(r => r.year1[s.key] || 0) }));
    stackedColumns($('chartSP'), {
        cats, series: spSeries, height: 300, topPad: 30,
        aria: 'Modeled first-year outflows for each annual review',
        tipHead: i => `<div class="pl-tip-note" style="margin:0 0 .3rem">Plan year ${R[i].first_year}</div>`,
    });
    legend($('legendSP'), spSeries);
    $('tableSP').innerHTML = tableHtml(['Report', 'Plan year', ...spSeries.map(s => s.name), 'Total'],
        R.map((r, i) => [r.label, r.first_year, ...spSeries.map(s => full(s.values[i])), full(spSeries.reduce((a, s) => a + s.values[i], 0))]));

    // Projection
    const P = DATA.projection;
    lineChart($('chartPJ'), P);
    $('tablePJ').innerHTML = tableHtml(['Year', 'Age', 'Inflows', 'Outflows', 'Net cash flow', 'Portfolio'],
        P.map(r => [r.year, r.age, full(r.inflows), full(r.outflows), signed(r.net), full(r.portfolio)]));

    // Net cash flow
    const notes = DATA.projection_notes.map((nt, i) => ({ ...nt, n: i + 1 }));
    cashFlowBars($('chartCF'), P, notes);
    legend($('legendCF'), [{ name: 'Surplus', color: 'var(--div-pos)' }, { name: 'Shortfall', color: 'var(--div-neg)' }]);
    $('tableCF').innerHTML = $('tablePJ').innerHTML;
    renderNotes($('notesCF'), notes.map(nt => ({ n: nt.n, title: `${nt.year} — ${nt.title}`, text: nt.text })));
}

async function init() {
    const vl = $('versionLabel');
    vl.textContent = VERSION_HISTORY[0].version;
    vl.title = `${COMMIT} · ${VERSION_HISTORY[0].description}`;

    try {
        const res = await fetch('plan_history.json', { cache: 'no-store' });
        if (!res.ok) throw new Error(res.status);
        DATA = await res.json();
    } catch (e) {
        $('plEmpty').hidden = false;
        return;
    }
    const R = DATA.reports, first = R[0], last = R[R.length - 1];
    $('plSubtitle').textContent = `${R.length} Fidelity annual reviews, ${first.label} – ${last.label}. Projections are Fidelity's hypothetical scenarios, not forecasts.`;
    $('subPJ').textContent = `Fidelity's deterministic projection from the ${last.label} report, in nominal dollars, out to age 95.`;
    if (last.monte_carlo) {
        const mc = last.monte_carlo;
        $('mcNote').textContent = `Monte Carlo (1,000 trials): median portfolio outcome ${money(mc.p50)}; 20th percentile ${money(mc.p20)}; 80th percentile ${money(mc.p80)}. Hypothetical — not a forecast.`;
    }
    $('plFoot').textContent = `Source: Fidelity / eMoney annual reviews. Real estate values are manual entries that stay fixed between updates. Data generated ${DATA.generated} by build_plan_history.py.`;
    $('plMain').hidden = false;

    renderTiles();

    document.querySelectorAll('.pl-seg-btn[data-scope]').forEach(b => b.addEventListener('click', () => {
        nwScope = b.dataset.scope;
        document.querySelectorAll('.pl-seg-btn[data-scope]').forEach(x => x.classList.toggle('active', x === b));
        drawAll();
    }));
    document.querySelectorAll('.pl-seg-btn[data-adj]').forEach(b => b.addEventListener('click', () => {
        adjusted = b.dataset.adj === '1';
        document.querySelectorAll('.pl-seg-btn[data-adj]').forEach(x => x.classList.toggle('active', x === b));
        drawAll();
    }));
    document.querySelectorAll('.pl-tbl-btn').forEach(b => b.addEventListener('click', () => {
        const on = b.getAttribute('aria-pressed') !== 'true';
        b.setAttribute('aria-pressed', on);
        const id = { nw: 'NW', sp: 'SP', pj: 'PJ', cf: 'CF', fc: 'FC', lv: 'LV' }[b.dataset.table];
        $('chart' + id).hidden = on;
        $('table' + id).hidden = !on;
        if (!on) drawAll();
    }));

    drawAll();
    let lastW = document.body.clientWidth, timer;
    window.addEventListener('resize', () => {
        clearTimeout(timer);
        timer = setTimeout(() => { if (document.body.clientWidth !== lastW) { lastW = document.body.clientWidth; drawAll(); } }, 120);
    });
}

document.addEventListener('DOMContentLoaded', init);
